### ISSUE TITLE
Re-upload to Pursuit

### ISSUE THREAD

**Issue by i-am-tom** [sharkdp/purescript-numbers#3]
Hello!

Pursuit has been reset ready for PureScript 0.11, so all packages need to be re-submitted. If you could do so, I have a PR that I'd like to make :)

Thanks!

**Comment by sharkdp** [comment]
Thank you for the reminder. I won't have access to my workstation for the next few days, but please feel free to re-submit to pursuit yourself. I believe it is not restricted in any sense. 

Looking forward to any contributions!

**Comment by i-am-tom** [comment]
Oh, wonderful - I'll have a go! Thank you :)

**Comment by sharkdp** [comment]
Done: https://pursuit.purescript.org/packages/purescript-numbers/
