### ISSUE TITLE
Use newtypes instead of type aliases

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/purescript-numbers#5]
.. for `Precision` and `Fraction` (as suggested by @hdgarrood here: https://github.com/purescript/purescript-prelude/issues/124)

**Comment by hdgarrood** [comment]
Come to think of it, do they need to be distinct? You're already saying which kind of comparison you want in the choice of function. Perhaps it might make sense to use just one newtype for both functions, and call it something like `Tolerance`?

**Comment by hdgarrood** [comment]
Just something to consider - I think what you have now is good too. :)

**Comment by sharkdp** [comment]
Hm.. I was also thinking of merging them, but somehow I wanted to make clear that they have a rather different meaning. The argument to `eqRelative` (`Fraction`) is a multiplicative factor while the argument to `eqAbsolute` is an (additive) constant. `Tolerance` is actually a much better name for the latter, so I changed that.
