### ISSUE TITLE
Add function(s) for converting Numbers to Strings

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/purescript-numbers#6]
As suggested by @natefaubion [here](https://github.com/purescript/purescript-prelude/issues/124). /cc @hdgarrood

It would be interesting to have a few basic functions for converting `Number`s to a `String`.

There are several packages dealing with (pretty) printing of numbers already:
- [purescript-number-format](https://github.com/Jonplussed/purescript-number-format) (@Jonplussed) - exports some available methods from JavaScript (`toExponential`, `toFixed`, `toPrecision`) and defines a few convenient helper functions (`toString`, `toHexString`, ..).
- [purescript-format](https://github.com/sharkdp/purescript-format) (@sharkdp) - pretty printing of integers and numbers, `Monoid`-based interface for defining the style.
- [purescript-formatters](https://github.com/slamdata/purescript-formatters) (@slamdata) - more ambitious project, also does date/time formatting.

In my opinion, merging *purescript-number-format* into this package or implementing a similar functionality would be the best option. The API of *purescript-format* is probably "too opinionated" for a low-level module like this.

What do you think?

**Comment by hdgarrood** [comment]
Yep, sounds sensible to me.

**Comment by hdgarrood** [comment]
One suggestion I'd have is to have newtypes for the scale or radix arguments in functions like toExponential so that actually formatting the number gives you a `String` and not a `Maybe String`.

**Comment by hdgarrood** [comment]
Newtypes where the constructor is not exported, that is, so that you can guarantee the value is within the range it needs to be in.

**Comment by sharkdp** [comment]
I went with a slightly different approach now, but it goes in a very similar direction to what you proposed.

https://github.com/sharkdp/purescript-numbers/blob/21cf05da5727969bb3e9ea08b45c30de68cafc14/src/Data/Number/Format.purs#L37-L62

**Comment by hdgarrood** [comment]
Looks really nice, great work :)
